chore: rename particle renderer
oasis-engine/manual pull request #12
Opened 2021-01-27 07:27 UTC by eyworldwide

Update the documentation of  particle renderer which is totally refactored.

2021-01-27 09:54 UTC, GuoLei1990 requested changes

2021-01-27 09:54 UTC, GuoLei1990 commented on zh-cn/component/particle-renderer.md
> +- [`angleRandomness`](${book.api}classes/core.particlerenderer.html#anglerandomness): 初始旋转角度随机因子，取值在 0~1 之间，例如：rotate 为 0，随机因子为 0，则生成的粒子角度均为 0，随机因子为 1，则生成的角度在 -PI~PI 之间随机。
Grammatical errors.

2021-01-27 10:11 UTC, eyworldwide commented on zh-cn/component/particle-renderer.md
> +- [`angleRandomness`](${book.api}classes/core.particlerenderer.html#anglerandomness): 初始旋转角度随机因子，取值在 0~1 之间，例如：rotate 为 0，随机因子为 0，则生成的粒子角度均为 0，随机因子为 1，则生成的角度在 -PI~PI 之间随机。
Fixed.

2021-01-28 02:35 UTC, GuoLei1990 approved these changes
+1

2021-01-28 02:36 UTC, merged